# Generated by Django 3.0.4 on 2020-03-25 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=200)),
                ('created_at', models.DateField()),
                ('updated_at', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=200)),
                ('event_type', models.CharField(max_length=200)),
                ('event_location', models.CharField(default='', max_length=50)),
                ('description', models.TextField()),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('city', models.TextField()),
                ('state', models.TextField()),
                ('country', models.TextField()),
                ('zip_code', models.CharField(max_length=10)),
                ('status', models.IntegerField(default=0)),
                ('cost', models.IntegerField(default=0)),
                ('created_at', models.DateField()),
                ('updated_at', models.DateField()),
                ('partner_tag', models.TextField()),
                ('partner_url', models.TextField()),
                ('image', models.ImageField(default='', upload_to='event/images')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Category')),
            ],
        ),
    ]
