# Generated by Django 3.0.4 on 2020-03-30 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20200326_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('event_name', models.CharField(max_length=200)),
                ('event_type', models.CharField(max_length=200)),
                ('event_url', models.CharField(max_length=200)),
                ('created_at', models.DateField()),
            ],
        ),
    ]
