# Generated by Django 3.0.4 on 2020-04-08 05:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0005_auto_20200408_1036'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventBookmark',
            new_name='Bookmark',
        ),
        migrations.RenameField(
            model_name='bookmark',
            old_name='event_id',
            new_name='event',
        ),
        migrations.RenameField(
            model_name='bookmark',
            old_name='user_id',
            new_name='user',
        ),
    ]
