# Generated by Django 3.0.4 on 2020-04-08 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_auto_20200408_1056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmark',
            old_name='event',
            new_name='event_name',
        ),
    ]
