# Generated by Django 3.0.4 on 2020-04-08 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_auto_20200408_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='event_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Event'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='event_name',
            field=models.CharField(max_length=200),
        ),
    ]
