# Generated by Django 3.0.4 on 2020-04-08 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_auto_20200408_1242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmark',
            old_name='event_id',
            new_name='event',
        ),
    ]
