# Generated by Django 3.0.4 on 2020-04-13 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='review',
            name='pub_date',
            field=models.DateField(verbose_name='date published'),
        ),
    ]
