# Generated by Django 3.0.4 on 2020-04-13 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_auto_20200413_1509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='user_id',
            new_name='user',
        ),
    ]
