# Generated by Django 2.2 on 2020-04-23 13:14

import django.contrib.gis.db.models.fields
from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_auto_20200413_1513'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='event',
            managers=[
                ('geo_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='geo_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
