# Generated by Django 2.2 on 2020-04-24 12:08

from django.db import migrations
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0013_auto_20200423_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='position',
            field=geoposition.fields.GeopositionField(default=1, max_length=42),
            preserve_default=False,
        ),
    ]
