# Generated by Django 2.2 on 2020-04-24 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0014_event_position'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='event',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='geo_location',
        ),
    ]
