# Generated by Django 2.2 on 2020-04-30 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0016_auto_20200424_1302'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='event',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='geo_location',
        ),
    ]
