# Generated by Django 2.2 on 2020-05-01 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0018_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_unread',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
