# Generated by Django 2.2 on 2020-05-06 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0021_auto_20200502_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='notificaton',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='notificaton_title',
        ),
        migrations.AddField(
            model_name='notification',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(default=-1.0, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_unread',
            field=models.BooleanField(default=False),
        ),
    ]
