# Generated by Django 2.2 on 2020-05-08 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0026_auto_20200508_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='city',
        ),
        migrations.RemoveField(
            model_name='event',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='event',
            name='longitude',
        ),
    ]
