# Generated by Django 2.2 on 2020-05-08 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0029_auto_20200508_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='address',
        ),
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
        migrations.AlterField(
            model_name='event',
            name='city',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='country',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='state',
            field=models.CharField(max_length=200),
        ),
    ]
